### ISSUE TITLE
Local server for p2p

### ISSUE THREAD

**Issue by subhendukundu** [syphon-org/syphon#117]
I am working on something similar but in a different approach, I feel we can contribute a lot to this.
I know dart already have [rpc](https://github.com/dart-lang/json_rpc_2). What's stopping to use here? I haven't use Matrix before. So you wouldn't need Matrix anymore if that works, correct?

**Comment by ereio** [comment]
[Matrix](matrix.org) is attempting to be a standard for communication, particularly instant messaging, in the way SMTP, IMAP, and POP3 work together to make Email. 
You could actually create a matrix server and client that [communicate via RPC](https://github.com/zhaytee/matrix-rpc-js), as matrix uses a RESTful api over https. In an effort to popularize the matrix protocol though, I will be sticking to using the matrix protocol as a means of communication. Let me know if I can do anything to clarify this.

The part of matrix team has already built a client that implements P2P (using libp2p) and matrix, you can [read about it here](https://matrix.org/blog/2020/06/02/introducing-p-2-p-matrix) or boot it up at https://p2p.riot.im
