### ISSUE TITLE
Support for Mozilla homeserver SSO

### ISSUE THREAD

**Issue by arunsathiya** [syphon-org/syphon#134]
It's not possible to login with Mozilla homeserver account at the moment, because they use SSO for login. Are there plans to support it?

Homeserver: mozilla.modular.im

**Comment by ereio** [comment]
no plans yet, but I'll look into it after this week. Group E2EE is the goal for the next release. Thanks for bringing this up, it's a popular home server.

**Comment by ereio** [comment]
just wanted to note here that this is scheduled along side several bug fix releases over the next couple weeks :)
