### ISSUE TITLE
UI Is too large — Content, buttons and text boxes are cut off

### ISSUE THREAD

**Issue by Wilker-a** [syphon-org/syphon#135]
![Example creenshot](https://user-images.githubusercontent.com/10854855/87493474-6864df00-c63c-11ea-922b-9b8d61afdf3c.png)

buttons and boxes have too much height and unused whitespace on a small screen like this too.

###### v0.0.16 as of now, under Android 5.1.1, with a total resolution of 480x800

**Comment by ereio** [comment]
I've been using an original iPhone SE for small screen testing, not sure hw this slipped through. Will be fixed in this weekends release
