### ISSUE TITLE
Implement "Work in Progress" visual cues

### ISSUE THREAD

**Issue by Wilker-a** [syphon-org/syphon#150]
while poking around the application, i quite often find infinite loading buttons and elements, buttons which does nothing or doesn't change, and screens i can't go to. so assuming that you're working in the core functionality before the glitter and buttons, i think it would be really useful to put some sprites or some colored text or something similar to indicate features that you've placed on the screen as planned features but haven't implemented yet. this would clear some confusion between features that are implemented or not at that time whenever people are hunting for any bugs. :3

just to remember, it's best to keep it as simple to place around and remove as an obvious placeholder can possibly be. \^_\^'

**Comment by ereio** [comment]
very good idea, ill comb through and do something like a toast or a 🛠 emoji around placeholders in the next release
