### ISSUE TITLE
Application freezes upon loading older messages

### ISSUE THREAD

**Issue by Wilker-a** [syphon-org/syphon#152]
the messenger consistently freezes whenever it finishes loading up and drawing (placing on the screen) older messages.

###### version 0.0.23 under Android 5.1.1

**Comment by ereio** [comment]
this will be addressed with the #166 issue as it's systemic due to Hive encrypting the serialized cache on the main thread.

(Hive doesn't play nicely with non-main thread serialization/encryption)
