### ISSUE TITLE
Multiaccount support

### ISSUE THREAD

**Issue by LibreHacker** [syphon-org/syphon#181]
Jabber clients like Conversations support it, and more other too.

But Matrix have problem with realization of this, maybe solve it in Syphon?

**Comment by ereio** [comment]
I agree. To enable SMS without matrix, we will need this path anyway. Have been thinking about adding it sooner rather than later due to needing it between my accounts as well. We'll use this issue to track it.

**Comment by grravity** [comment]
Big +1 to this

**Comment by ereio** [comment]
@grravity definitely wouldn't take much work with the way Syphon is structured. Probably will be scheduled in after key imports/exports, which is next after I finish the cache overhaul in 0.1.4 :)
