### ISSUE TITLE
"quit editing" in Set up Profile

### ISSUE THREAD

**Issue by LibreHacker** [syphon-org/syphon#182]
You think it's really need button?

Maybe left top button arrow save-only?

**Comment by ereio** [comment]
I wanted to have a button that users could choose to cancel with and be certain no changes were made to their profile. Maybe "cancel" is a better word? It's up for debate but I'd still want something to serve that purpose.

**Comment by LibreHacker** [comment]
Sorry for later answer, i think can be use "Cancel".
