### ISSUE TITLE
Initial sync caused synapse crash

### ISSUE THREAD

**Issue by MTRNord** [syphon-org/syphon#185]
Hi, I tried the play store version and this is the first client that was able to crash my synapse in seconds.

This is not normal initial sync behaviour. I am not sure why but I am guessing some kind of requests happen way too often on initial sync. Usually, this shouldn't happen on my account. with element for example no issues are happening on my initial sync.

**Comment by ereio** [comment]
I'll look into this. While the initial sync is happening in the background, Syphon runs a "quick sync" which just pulls the names of the rooms and the first 10 messages in an effort to load faster. It may have just overloaded your synapse server. I'll try adding a throttle / batching the quick sync

**Comment by MTRNord** [comment]
Do you use lazy loading yet? As not doing it is expensive and I am not sure if I saw that in the code.

**Comment by ereio** [comment]
Had several issues with lazy_loading when I first started the project last year. Probably is fine now and I'll add it to the needed stability work in 0.1.4/0.1.5 👍 it's likely just the full_sync happening upon logging in
