### ISSUE TITLE
syphon will not install

### ISSUE THREAD

**Issue by crtn32002** [syphon-org/syphon#187]
I have a LG ARristo 2 and I've been doing everything to keep this phone up to date but for some reason keep on giving me the bone compatible.

**Comment by ereio** [comment]
Does it give an error message as to why outside not compatible? 

Not sure what else to test for the specific device, but I'm sorry it's not working :(

I've tested on several fairly old phone emulators and haven't had any problems. I'm going to close the issue but feel free to reopen it if you want me to take another look. If you still can't get a newer phone yet, I can see if I can order the LG Aristo 2 to test!

Or if you want I'm even down to send you my old Google Pixel (1) device for free, which I've used successfully as a test device. Just let me know!

**Comment by ereio** [comment]
@crtn32002 Let me know if you'd still like help with this, otherwise closing for now
