### ISSUE TITLE
.well-known discovery

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#194]
Some Matrix servers are hosted on an entirely different actual address than the one in the users Matrix ID. E.g. users on the mozilla.org server has their Matrix ID ending with :mozilla.org, but the server is actually hosted at mozilla.modular.im
It is a technical detail that users shouldn't have to think about. It should be enough to enter their Matrix ID, and Syphon should do the server discovery based on the second part of the Matrix ID.

**Comment by ereio** [comment]
@notramo Syphon does check the .well-known endpoint of servers before attempt to log the user in. The code to handle this process [can be found here](https://github.com/syphon-org/syphon/blob/main/lib/store/auth/actions.dart#L304). Are you having trouble with a particular server?

**Comment by ereio** [comment]
@notramo confirmed working again outside github
