### ISSUE TITLE
typo in scheme name

### ISSUE THREAD

**Issue by emdete** [syphon-org/syphon#200]
the light theme is named "night" in the button in the settings (that one that cycles through the different color schemes) - or is that an intended typo?

**Comment by ereio** [comment]
There should actually be a theme named "night" and should be the darkest colored theme. Is it still appearing as a lighter theme for you? I just tried toggling it in 0.1.4 and it appeared to be displaying colors as expect.

**Comment by emdete** [comment]
yes, current version works as expected.
