### ISSUE TITLE
giving the matrix-id at login is difficult

### ISSUE THREAD

**Issue by emdete** [syphon-org/syphon#201]
if one knows  the matrix scheme for names its difficult to login with syphon because it adds the "@" in front. in one of the different login dialogs this is nicely reflected in the inputbox (that one adds the homeserver as domain as well as far as i remember), in another it's a blind flight.

i like the idea to have *one* domain (homeserver) and *one* nickname which builds the matrix id (never understood why other clients handle that differently) but for those knowing the form of the matrix id it would be helpful to show the resulting id.

finally you could check for @ and : and act accordingly to figure out what the user meant (assuming more than one @ or : is not allowed as a matrix id).

**Comment by ereio** [comment]
Thanks for bringing this up. If I understand you correctly, the login username field should already work as you've suggested, by parsing the username and homeserver out if formatted like @username:homeserver.org. I'm going to revisiting the login/signup flow this week and make sure everything is formatted as expected and consistent in the way it's presented.

I'll follow up here once I've combed through it again and confirm with you that it's no longer difficult / inconsistent.

**Comment by manuelliebchen** [comment]
I don't know if I should open an new issue but I have a similar problem with the home server port.
In die end the hostname is followed by the port of the server and now I don't know where to put the server address and if the port should follow or not. 
Also should the server be added by login under the username field?

**Comment by emdete** [comment]
i would like to clairify if the homeserver and the domain in the matrix-id may differ. if so the complicated login procedure makes sense. if not a simple "give id and password" or "give name, homeserver and password" would be better, in the second case the generated matrix-id should be shown.

element is even worse here and complicates thinks alot, syphon is alot nicer but could be improved. 

btw: the search button shouldnt be a questionsmark (looks like a help function) but a magnifier or such.

**Comment by ereio** [comment]
@emdete Hey! I was wondering if you could check out the current version release (0.1.6) and see if you thought the signup / login process was any better. Still a couple things to improve there, but I can make separate issues for those, such as allowing one @ symbol to be typed into the login username field. Let me know your thoughts, otherwise I'll close the issue after a while.

**Comment by ereio** [comment]
@manuelliebchen the port number found in the .well-known should be included in the requests made after login. Try again in the new version (0.1.6) and let me know if you're still having issues. The new version handles .well-known files much better

**Comment by ereio** [comment]
I'm going to close this issue after the 0.1.7 release if no one has any objections. Feel free to open a new ticket if you feel later it still hasn't been solved.

**Comment by emdete** [comment]
I'm stuck on #240 currently, if you could help there i can test the new login.

**Comment by ereio** [comment]
@emdete if you're willing, try this latest build. It was built by one the contributors and links to the latest PR.

If you want to still attempt building, the instructions for adding that package you're having trouble with in #240 should be under the desktop setup (it needs intl 0.17.0 as a dependency override when building on the flutter dev branch)

[https://an-atom-in.space/ci/build/syphon/main/2021-02-19T20:12:12+00:00/app-arm64-v8a-release.apk](https://an-atom-in.space/ci/build/syphon/main/2021-02-19T20:12:12+00:00/app-arm64-v8a-release.apk)

**Comment by ereio** [comment]
Didn't mean to close this one

**Comment by ereio** [comment]
After reviewing the original request and the way the login / signup screen works now, I think I've resolved the ask here. Happy to reopen this if you think it's still difficult @emdete. Thanks for the due diligence and testing! :)
