### ISSUE TITLE
client fails to sync data

### ISSUE THREAD

**Issue by NANASHI0X74** [syphon-org/syphon#218]
I got interested in this because I was looking for alternatives to element-android... I've managed to login, but currently my app looks like this
![Screenshot_20210123-130909_Syphon.png](https://user-images.githubusercontent.com/17546398/105577915-d53ffb00-5d7c-11eb-99db-3391e0433c3a.png)
and I can't really do anything.
Immediately after login I got a "failed to symc data" and an "unknown error" snackbar.
I found a sync option in the settings, that fails as well. Is there any way to get debug logs from the app or something like that?
(I'm running my own synapse instance btw)

**Comment by NANASHI0X74** [comment]
actually, I tried logging in again and I actually got "failed to fetch current user profile" and two unknown errors.
Also, it looks like the login succeeded in principle, since the syphon session shows up in my other clients

**Comment by ereio** [comment]
Really strange, but I think I know what might have happened. I'm fixing up the login / signup flow now to be more clear around picking or inputting homeserver domains.

Did you login with your matrix username with your root domain or the base_url? (i.e. @user:example.org vs @user:matrix.example.org)

**Comment by NANASHI0X74** [comment]
with the root domain... And the .well-known file I created should work

**Comment by ereio** [comment]
Sounds good. Only reason I asked is someone had done so and reported the same error state (authenticated properly with failed syncing).

Might be an issue with how Syphon handles values in the .well-known then. If you don't mind letting me know your homeserver domain (you can share privately through a message on matrix @ereio:matrix.org) I could take a look and make sure I'm not parsing something incorrectly. Otherwise, you could try again when 0.1.6 is released and see if the clean up work around homeserver domains fixes the issue after login. Either way, I'll keep an eye out.

**Comment by NANASHI0X74** [comment]
sure 😁 I sent you a message

**Comment by ereio** [comment]
Hey @NANASHI0X74! Version 0.1.6 should now be out for iOS and Android. Let me know if syncing now works. There are two flows to login with a specific homeserver and I'm curious if one of them was broken:

1. typing in @example:example.org and resolving the hostname from the userId
2. searching for the homeserver and selecting it, which will update the homeserver for the userId field and login

If you could, let me know if any of these fail or succeed now. Thanks again for your help with this. I appreciate it!

**Comment by NANASHI0X74** [comment]
looks like both methods fail. I just noticed that for flow 1 I had to tap the login button twice... The first time the button displayed a circular progressindicator for a few seconds and then nothing happens and the second time I get to the screen where it says no messages

**Comment by ereio** [comment]
Setup a homeserver under my blog domain and found the issue! Going to fix several more issues and put a new build out in the next couple days 👍
