### ISSUE TITLE
Support for Autofill

### ISSUE THREAD

**Issue by NANASHI0X74** [syphon-org/syphon#219]
Hi, I'm using https://github.com/android-password-store/Android-Password-Store as a password manager on Android. I noticed that the login field in the app didn't get picked up as an autofillable field. Wether or not you want to support autofill I suppose you will have to decide yourself, but in flutter for autofill to work ~~you need to wrap inputfields in some seperate widgets apparently~~ actually it looks like it's not quite correct that you need to wrap them in another widget, instead, if I understand correctly, there's a property on textfields (https://api.flutter.dev/flutter/material/TextField/autofillHints.html) to set and there's also an autofillgroup widget that I think can group multiple textfields together so they can be autofilled at the same time (I haven't got round to using them yet myself)
 - https://api.flutter.dev/flutter/services/AutofillHints-class.html
If you're already using those, then this must be a bug :p

**Comment by ereio** [comment]
Thanks for doing the research!

I can't think of any negatives but if someone knows better let me know.

Otherwise, I'll throw this into the next release.
