### ISSUE TITLE
Performance degrades as more message history is loaded.

### ISSUE THREAD

**Issue by git-bruh** [syphon-org/syphon#230]
Initially, activities like scrolling, typing etc. are smooth in all rooms, but as you keep scrolling up and fetching message history, the performance for that particular room slows down. Seems to be related to syphon loading the complete cached message history at once

So if i load a lot of history in a room, tapping on the room in the room list is slow to open, scrolling the chat and message input, both are laggy ONLY in that particular room. The same starts happening to any room where a lot of history is fetched.

#226 seems to be caused by this issue in my observation.

**Comment by ereio** [comment]
Very helpful research into the issue and saved me a lot of time. I really appreciate it. 

There's a lot of message filtering happening on the UI thread when entering rooms that I've wanted to move, it just hasn't been the bottleneck until now. Additionally, as you mentioned, there's a lack of pagination when viewing a room. Though ideally, one should be able to view a lot of history at once without a performance issue.

I'll work on these as a fix, along with some cold storage changes that should help, in the upcoming bugfix release.
