### ISSUE TITLE
'm.identity_server' should not be required in .well-known

### ISSUE THREAD

**Issue by zecakeh** [syphon-org/syphon#234]
According to the [client-server spec](https://matrix.org/docs/spec/client_server/r0.6.1#well-known-uri), the `/.well-known/matrix/client` is valid if `m.homeserver` is valid and if `m.identity_server` is valid or missing.

The verification implementation at https://github.com/syphon-org/syphon/blob/0dc9e107a496bd4aabe7b18ece0b2161a6b5c102/lib/store/auth/homeserver/actions.dart#L15 only considers a `.well-known` file valid if both are valid.

I also wonder if there should be a fallback that would check if the url provided is a valid `base_url` by fetching an endpoint like `/_matrix/client/versions`, because I don't believe that the `.well-known` file is required.

It should be noted that as a user I wasn't warned that the url I entered was not a valid matrix server

**Comment by ereio** [comment]
Just oversight on my part in regards to the m.identity_server piece. Will fix in another bug fix batch this weekend.

I planned on indicating valid server status to the user in the homeserver search with a red X or green ✔️, just didn't make it into the latest release.

Good idea with checking version on the base_url, I'll add that in with a valid server status indicator 👍 Thanks!
