### ISSUE TITLE
Keyboard keeps getting dismissed

### ISSUE THREAD

**Issue by git-bruh** [syphon-org/syphon#236]
They keyboard gets dismissed on sending a single message, I don't think that this is desirable behaviour since it's annoying and [this](https://stackoverflow.com/questions/55863766/how-to-prevent-keyboard-from-dismissing-on-pressing-submit-key-in-flutter) is linked in references.

**Comment by ereio** [comment]
I'll change the default to not dismiss, and add an option to toggle keyboard dismiss after send 👍
