### ISSUE TITLE
Not all chats are listed (greyed out)

### ISSUE THREAD

**Issue by toger5** [syphon-org/syphon#238]
Some chats are just greyed out and not listed.
The picture shows the top part of my chat list:
<img src="https://user-images.githubusercontent.com/16718859/107629082-e1272a80-6c61-11eb-8431-8b5fbd70a819.png" width="300"  />

there are about 100chats. I can still scroll through all the chats. (I need to scroll back up to get back to the top, so they are listed but not rendered properly) 
clicking on them also does not work.

**Comment by ereio** [comment]
Very strange issue. I'll look into it but not sure how to recreate.

 It looks like the "blocked" symbol is next to the avatar so that actually means your session has been signed out of matrix or is no longer authenticated. One of the upcoming solutions I had for this was a dialog password prompt to re-authenticate or wipe local storage and return to the home screen.

Just to confirm, are you on version 0.1.6 or above?

**Comment by TR-SLimey** [comment]
Same "symptoms" as I get in #239 so this may be the same bug. I'll leave mine open for now since it provides some more details but feel free to close it if it is indeed a duplicate.

**Comment by TR-SLimey** [comment]
@toger5 Would you be able to confirm whether any of the rooms had their topic changed recently?

**Comment by mahdi1234** [comment]
Checked with https://an-atom-in.space/ci/build/syphon/main/2021-02-19T20:12:12+00:00/app-arm64-v8a-release.apk and it worked for me.

**Comment by toger5** [comment]
@ereio Yes i am on 0.1.6
I also tried a full resync. (Log out, log in)
It first fills the list with all chats. They are coming in one by one (quickly) than they all disappear and only some (2-5) reappear. The ones that reappear are rooms witg very recent events in them but not the most recent ones

**Comment by TR-SLimey** [comment]
@toger5 would you be willing to try the version in the link provided by @mahdi1234 to see if there's any improvement? It's a development build with the latest changes (built by me) which should contain the fix.

**Comment by toger5** [comment]
Just tried is. I get the exact same behaviour. (Same rooms are missing)

**Comment by TR-SLimey** [comment]
Ah. That's not good :|

In that case I can only suggest building a debug build from source which would display an error message onscreen when this happens so it's easier to debug. If you'd be able to do that that would be great, otherwise I'll have to leave further debugging to ereio.

**Comment by mahdi1234** [comment]
@TR-SLimey just to let you know I'm having this issue back again after I did following

- I found it a little bit annoying that for some reason my irc.oftc.net bot/bridge was always on top of the list of rooms (it creates when one subscribes to any irc chat on that server, did long time before started using syphon)
- went to the settings and disabled "toggle direct room" off

after that I'm back to the original issue, restarting app or wiping cache doesn't help. Maybe it will help in identifying the culprit.

**Comment by TR-SLimey** [comment]
@mahdi1234 thanks! Any additional information is useful. I think this might actually be several issues all to do with handling errors displaying rooms in the room list.

**Comment by toger5** [comment]
This is still present for me and makes the app basically unusable.
Just want to ping the issue because it might put off a lot of potential testers

**Comment by ereio** [comment]
thanks for bumping this. I'll take a look this week/weekend

**Comment by toger5** [comment]
Let me know if i should test with a specific apk. Or if I should perform a specific order of operations and inform you about the behaviour on my device/ with my matrix acc

**Comment by 0x1a8510f2** [comment]
@toger5 I think what might be good is if you run a debug version as that should display a red screen with an error instead of grey, which should give more information. Let me know if you'd like me to build the debug version for you.

**Comment by toger5** [comment]
Actually that would be nice. I dont have the flutter toolchain installed anymore.

**Comment by 0x1a8510f2** [comment]
@toger5
I've set my CI to do it: https://ci.0x1a8510f2.space/0x1a8510f2/syphon/95/1/3
The build should be somewhere in https://0x1a8510f2.space/ci/build/syphon-debug/ (the folder should 404 now but be created when the build finishes which can take up to an hour total on my terrible CI server)

I'm off to do some other work, ping me here or on [Matrix](https://matrix.to/#/@tr_slimey:an-atom-in.space) if something screws up :P

**Comment by toger5** [comment]
![Screenshot_20210610-001629.jpg](https://user-images.githubusercontent.com/16718859/121437126-0e6eb580-c982-11eb-990c-7340ed77abba.jpg)

The same issue occured. Here is the error

**Comment by 0x1a8510f2** [comment]
Yeah, that error is what I was looking for. Less descriptive than I imagined but it's always something. Thanks! Should hopefully make things easier to debug.

**Comment by N4chtSchatten** [comment]
I'ld like to add that, when scrolling down all the way through the grey area, the chats seem to appear at the bottom. (The empty chats seen here, is because I left those rooms, it's just a test account.)

![IMG_1609](https://user-images.githubusercontent.com/85883544/121899422-b2f74b80-cd24-11eb-93ff-486ac980e596.PNG)
![IMG_1610](https://user-images.githubusercontent.com/85883544/121899426-b38fe200-cd24-11eb-9fd4-d9f570df2284.PNG)

**Comment by ereio** [comment]
I'm fairly confident I found and fixed all of the issues causing this. I've managed to recreate it in more ways than one. I'm going to close this under version 0.1.9, but do not hesitate to reopen the issue if you see it crop up again!
