### ISSUE TITLE
Roomlist breaks in specific conditions (possibly room topic change)

### ISSUE THREAD

**Issue by TR-SLimey** [syphon-org/syphon#239]
I have not been able to reproduce this again after it happened initially, so I haven't been able to fix it, but just a heads-up - in certain conditions the roomlist fails to load properly displaying some (not all) rooms and a grey screen below them. It does not seem to be a race condition as this happened simultaneously in both my development instance of Syphon and the production gplay version (both linked to the same account), which leads me to believe that it's down to an event that was sent in one of the rooms. The debug version displayed the following error also:

<details>
<summary>
Screenshot
</summary>

![image](https://user-images.githubusercontent.com/37966924/108057259-502dc600-704a-11eb-94cf-36798574fe51.png)

</details>

And from that and a quick `grep` of the source, I'm reasonably sure that the bug exists in `lib/store/rooms/room/selectors.dart`, specifically on line `15` or line `20`.

One of those is responsible for generating the topic preview and I have indeed edited the topic in one of the rooms recently, so that may be it, but I'll have to leave further debugging to you :P

**Comment by ereio** [comment]
Thanks so much for this debugging work! I'm going to do some error handling / better formatting around both Topics and Message previews. My suspicion is that this happens when attempting to preview a message that was redacted (the ```body``` of a message event becomes ```null``` when deleted / redacted)

**Comment by TR-SLimey** [comment]
No worries! :D
I think you're probably right about it being to do with redactions also. My initial thoughts were that it might be to do with clearing the topic but not sure if that produces an empty string or a null.
