### ISSUE TITLE
Wont build

### ISSUE THREAD

**Issue by emdete** [syphon-org/syphon#240]
Because F-Droid is stuck at 0.1.5 i tried to build myself. I get the error

```
$ flutter pub get
Because syphon depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because syphon depends on intl ^0.16.1, version solving failed.     
Running "flutter pub get" in syphon...                                  
pub get failed (1; So, because syphon depends on intl ^0.16.1, version solving failed.)

```

No clue what's wrong, searching the internet doesnt reveal something useful to me.

**Comment by ereio** [comment]
F-Droid should have the updated version (0.1.6+3), let me know if you have any issues with it. 

It seems you may have been on the dev version of Flutter (instead of the stable branch) as that dependency bump is required for dev Flutter branch / desktop builds.
