### ISSUE TITLE
Username issue

### ISSUE THREAD

**Issue by BSiddharth** [syphon-org/syphon#257]
Are there any rules/limitaions on the username? Cuz even random usernames get denied. It would be helpful if user can be informed about why a specific username has been denied. And same goes with the password , any random 4 words (as asked on the text on the password page) doesnt work but 7 random words do get accepted?

**Comment by 0x1a8510f2** [comment]
Both of these are almost entirely dependent on the homeserver as opposed to the app AFAIK, though maybe there's a way to make the errors a little more verbose.

**Comment by BSiddharth** [comment]
I see about usernames but password can be changed then because that is just straight out wrong info right?

**Comment by 0x1a8510f2** [comment]
I'm not sure what you mean, could you clarify? In regards to passwords, the homeserver may enforce a certain password length/strength.

**Comment by BSiddharth** [comment]
yes if homeserver defines the rules and let say which is 7 in our case then the 4 word info on the screen was straight wrong right. Instead of saying type any 4 words it can be more clear by saying that every homeserver has different rules but if you are on the matrix.org homeserver then this this this

**Comment by 0x1a8510f2** [comment]
Ah, I see what you mean. Yeah, that make sense. I think the 4 words advice is just generic password strength advice, but I agree that it could be misleading if the homeserver requires special chars and the likes.

**Comment by ereio** [comment]
Yeah, it's just generic advice but I've run into the same issue when trying signup on other homeservers. I'll look at ways to solve this. I don't personally like the default minimum requirements as I don't think they're strict enough, but I may have to change the messaging to be more generic and follow the spec defined here

https://matrix.org/docs/spec/client_server/latest#notes-on-password-management
