### ISSUE TITLE
SSO Github

### ISSUE THREAD

**Issue by ueen** [syphon-org/syphon#260]
Hey, can't login with SSO via github on matrix.org, maybe you can take a look at fluffychat they have a nice flow where a website is opening and you can select any SSO provider available :)

Also any plans for voice messages? 😍

**Comment by ereio** [comment]
Hey! Sorry for the inconvenience. I'll take a look for the next deployment and see if I can slot this in :)

Multimedia messaging is the next thing planned after Cross Signing and Verification work! Definitely a personal want as well 👍
