### ISSUE TITLE
In message TextField, enable autocorrect and enableSuggestions

### ISSUE THREAD

**Issue by kalenpw** [syphon-org/syphon#268]
Hey there,

So far I have been thoroughly enjoying this app and think it has potential to be the best iOS (and other platforms) Matrix Client. 

I noticed the TextField used for entering messages has autocorrect: false and enableSuggestions: false.   Is this done for a specific reason/would you consider changing it? 

I think most people will expect autocorrect to be the default. 

If it is done for privacy reasons I wonder if a default of false with a setting to enable it to true would be feasible.

**Comment by ereio** [comment]
Someone else just mentioned the keyboard seemed off on iOS. This was for privacy reasons, mostly in regards to Android, but I think we could make it both toggle-able and on by default on iOS. I'll try to plop this into one of the next releases 👍

**Comment by kalenpw** [comment]
Looks great in the latest update now 👍
