### ISSUE TITLE
Cant set profile pic

### ISSUE THREAD

**Issue by Kreuger** [syphon-org/syphon#271]
I am unable to set a profile pic. When I choose one from the gallery, it just goes back to my profile and doesnt set. This issue was also in 0.1.8.

**Comment by 0x1a8510f2** [comment]
Can reproduce in latest (`0.1.9-alpha`). Appears to fully work in `0.1.6+3-alpha`. Partially broken in `0.1.7+1-alpha` whereby the image appears on the profile but there is no way to save the change. Fully broken in `0.1.8+1-alpha` and above whereby the image no longer even appears on the profile, and the "Photo Select Method" dialogue doesn't hide after selecting a photo. Tested on Android 10.

**Comment by Kreuger** [comment]
Just wanted to come back and say that its working in 0.1.10. Thank you!
