### ISSUE TITLE
No way to log in with user/pass if homeserver supports SSO

### ISSUE THREAD

**Issue by 0x1a8510f2** [syphon-org/syphon#279]
[As reported](https://matrix.to/#/!TuUZlBCzpspzkrTASf:matrix.org/$4IpY2j3UucBvxK4sSXp2JrdZXefqWo-54pjO1gYeQRc?via=matrix.org&via=mozilla.org&via=privacytools.io) by [@surak:gnomos.org](https://matrix.to/#/@surak:gnomos.org) and [@olivier:kevread.fr](https://matrix.to/#/@olivier:kevread.fr):

>I just tried to login to my home server with my user/pass but as I have SSO enabled I only see the SSO button and the password field goes away and I can't login

I have not checked this myself

**Comment by ereio** [comment]
It's an issue. Noticed it just after deploying 0.1.9 and forgot to create an issue. Going to comp up the SSO login button to appear alongside normal user/pass
