### ISSUE TITLE
Theme behaviour different between debug and production builds

### ISSUE THREAD

**Issue by 0x1a8510f2** [syphon-org/syphon#284]
> As I update Syphon from the Play Store today, I am delighted to learn that my recent changes have made it to the official release, and that I will now be running all this code that I have recently written. How exciting! Yet, to my horror, the FAB just refuses to change colour without the app being restarted!
> 
> "Impossible", I exclaim, for I was sure that this bug has long been accidentally squashed as part of my theming refactor, "how could this be?!"
> 
> With sweat dripping down my face, I open Android Studio and re-run the `main` branch with my changes included.
> 
> The app builds slowly while my fans spin up...
> 
> "Could it be that my fix was but a figment of my imagination? Nothing but a dream, a glimpse of success I was just not destined to achieve?"
> 
> Warnings pop up on the console, the emulator boots up. My heart briefly stops as the splash screen of the app flashes on the screen...
> 
> "This is it."
> 
> In an adrenaline-fuelled frenzy, I change app primary colours with speed I never knew I was capable of but... Lo and behold... The FAB keeps up with my challenge. It explodes with a riot of colour, in all shades permitted by the "Select Primary Color" dialogue, without requiring so much as a touch of the back or home buttons.
> 
> "How can this be?!"
> 
> I stare in horror as the truth of the matter dawns on me. My face goes pale with realisation.
> 
> "The debug and production builds are different!"
> 
> And then, like a sudden gust of cool and pleasant wind carrying the smells of the most beautiful flowers, another thought crosses my mind:
> 
> "Ereio can take care of this!"

So here I am, clueless as to the cause, and opening a bug report in hopes that you can figure something out :P

This could be related, but I'm not really sure: https://github.com/flutter/flutter/issues/20342

Worth noting is that the issue also affects the top app bar. In the production builds, it always follows the "app bar color" while in debug builds it only does so in light theme, but in darker themes it actually seems to use the theme background colour.

This doesn't appear to be caused by my theme refactor as commit 9d1aaab1f7bdc4814dd1575e2babe5a7290f3663 seems to have the same issue.

Tested on Android 10 building with flutter 2.2.2 in Android Studio on openSUSE Tumbleweed. My CI builds are production and exhibit the same behaviour as official builds. The one debug build I did a while ago in my CI has the same behaviour as my Android Studio builds.

**Comment by ereio** [comment]
looking into this now 👍

**Comment by 0x1a8510f2** [comment]
Thanks! :P

**Comment by ereio** [comment]
has to do with upstream changes made to `fab-circular-menu`, not theming as a whole. Going to use my fork of the project and reference that instead. They're using `kReleaseMode` in several places that functionally change how it works across dev / prod.

**Comment by 0x1a8510f2** [comment]
Interesting. So effectively, that's intentional in their end? What about the app bar, since that seems to change behaviour too?

**Comment by ereio** [comment]
> Interesting. So effectively, that's intentional in their end? What about the app bar, since that seems to change behaviour too?

Not sure, I haven't been able to recreate this yet but attempting now

**Comment by ereio** [comment]
> @0x1a8510f2 and I triaged these issues and found some were bugs and some were features :)

what a narrative btw 👏

**Comment by 0x1a8510f2** [comment]
Thanks! 😆
