### ISSUE TITLE
Known user not found.

### ISSUE THREAD

**Issue by AnisTaluqdar** [syphon-org/syphon#289]
In element, there have an option to see known users. With this known user option you can easily find out your bridge network connected contact otherwise it is not possible so if there was an option for known users it would be great.

**Comment by ereio** [comment]
Can you share where you see this in Element / a screenshot of the option? AFAIK this configured as a server side config option and I don't have any home servers with this enabled. Thanks in advance!

**Comment by 0x1a8510f2** [comment]
I think they might be referring to this:

![Screenshot_20210710-172358.png](https://user-images.githubusercontent.com/83190128/125169785-a808cd00-e1a3-11eb-9eb2-b40127496e99.png)

Under the "new DM" bubble.

**Comment by ereio** [comment]
ah, wasn't checking mobile 👍

**Comment by ereio** [comment]
ah, wasn't checking mobile 👍
