### ISSUE TITLE
Text sending box color in dark mode 

### ISSUE THREAD

**Issue by aniseeo** [syphon-org/syphon#290]
![Screenshot_2021-07-08-12-23-51-07](https://user-images.githubusercontent.com/41234183/124872759-78ad6100-dfe7-11eb-8610-935ddfa08bd7.jpg)

I like all the UX designs about this app except this color.
Can you make it another color like dark or something else or give it an option to change the color of this box.  Also sending button color in the dark mode gray is better than white color.

Thanks 😍

I like your app.

**Comment by aniseeo** [comment]
![Screenshot_2021-07-08-13-03-25-97](https://user-images.githubusercontent.com/41234183/124877501-f45ddc80-dfec-11eb-83bf-35a9835c73da.jpg)


Like this way 🙃

**Comment by ereio** [comment]
I agree! The color isn't great and iirc this is the color due to a quick fix needed several versions ago. We'll make changes to make it look more like the other input field you posted here 😉

Thank for the kind words and appreciate the feedback! 👍

**Comment by 0x1a8510f2** [comment]
Working on it right now, should be ready soon :D

**Comment by 0x1a8510f2** [comment]
What do you think, @aniseeo ?

https://user-images.githubusercontent.com/83190128/125163077-43d61100-e183-11eb-83d4-ea85c442f78f.mp4

**Comment by aniseeo** [comment]
> What do you think, @aniseeo ?
> 
>  syphon-send-rework-demo.mp4

aww, thanks. It's very nice.
