### ISSUE TITLE
Multiaccount support

### ISSUE THREAD

**Issue by genofire** [syphon-org/syphon#295]
It would be nice, if it is possible to have in one Client multiple accounts. E.g. for private, job, actisivm and OpenSource-Developing.
And the Option to enable and disable single accounts.
(Also there Notification - maybe by time ala quiet Hours)

**Comment by ereio** [comment]
this is a duplicate of #181. Definitely appreciate the ask and am hoping to get this out soon. Would you mind if I close this duplicate?

**Comment by genofire** [comment]
Yes, sorry not found/Seen.

Closed becouse of duplication
