### ISSUE TITLE
Support for XMPP too

### ISSUE THREAD

**Issue by Porrumentzio** [syphon-org/syphon#299]
XMPP protocol (called Jabber in the past), which I like best than Matrix as the servers are easier to set up and maintain, is missing modern, comfortable apps. Syphon is great in this aspect and it would be wonderful if Syphon would be a client for XMPP too.

Here are some libraries: https://xmpp.org/software/libraries.html

**Comment by toger5** [comment]
I think the ideology of matrix is such, that this should not be handled by clients. As soon as a client is capable to communicate with the matrix protocol the servers can bridge to XMPP (https://matrix.org/docs/projects/as/matrix-xmpp-bridge) So using syphon as an xmpp client is than possible.
Of course that would mean you still need to setup a matrix server for the bridging. Or you find a public instance that does the bridging for you.

**Comment by ereio** [comment]
@toger5 summed up what I would have said in regards to getting what you want now.

I thought a while back about making Syphon something akin to Pidgin, or how that may naturally happen over time, but that's a much bigger task and I'm already strapped for time. If Pidgin happens to be discontinued in the future, I'd consider taking over the effort in some form. For the foreseeable future, Syphon will only target the Matrix client spec, with the only exception potentially being the p2p integration.

I'm closing this issue, but I appreciate the ask and will use this issue for XMPP support tracking if it were to be prioritized. If Syphon were to become stable enough long term, I wouldn't rule out implementing other chat _protocols_ like XMPP. That may be where Pidgin and Syphon would differ, in that it also supports non-standardized platforms.
