### ISSUE TITLE
IOS syphon latest version can not display right chinese words

### ISSUE THREAD

**Issue by cnmade** [syphon-org/syphon#302]
Hello, I am using IOS syphon latest version, and see it can not display right chinese words.

**Comment by cnmade** [comment]
May be should using UTF8 decode for json ?
![image](https://user-images.githubusercontent.com/278153/126262674-73df2421-dadc-464e-a0dc-fc91cbfbddcd.png)

**Comment by ereio** [comment]
This should be fixed in version 0.1.14 upon release. Let me know if you still see this issue after the update. Thanks!
