### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by menturion** [syphon-org/syphon#304]
Please find attached a first proposal for a German translation: [de.json.txt](https://github.com/syphon-org/syphon/files/6862553/de.json.txt)
Corresponding references have to be made within the source code. 

Question:
Could you please explain the meaning of "`take back the chat`" in "title-login".  I didn't translate this phrase.

FIX of English translation (`en.json`):
Please replace `Backgound` by `Background` for "content-notification-background".

**Comment by ereio** [comment]
"take back the chat" was a playful consonance phrase presented at login but has since been removed. No need to translate it.

Feel free to open a PR with these changes unless you'd like for me to incorporate them as is.
