### ISSUE TITLE
Messages do not decrypt after verifying

### ISSUE THREAD

**Issue by pythonInRelay** [syphon-org/syphon#307]
Messages sent on another platform eg. web browser do not decrypt even after verifying the Syphon instance.

They simply stay as "Encrypted message".

Sending a message on Syphon is visible on other platforms though. I have forced a sync and closed the app multiple times.

**Comment by ereio** [comment]
Looking into this today. Just to confirm, this is with a new chat you created after logging in with Syphon? 

Existing encrypted chats are not decryptable yet due to disabled key imports and unimplemented key sharing. This is currently being worked on with the cross signing effort though

**Comment by pythonInRelay** [comment]
Hi,

No this is with chats that already exist. No problem, as long as you know about the issue that's fine. I'll close this.
