### ISSUE TITLE
Account switcher looks off on dark theme

### ISSUE THREAD

**Issue by 0x1a8510f2** [syphon-org/syphon#336]
As visible in the image below, the background of individual accounts in the account switcher looks odd in dark themes. It should probably be a little darker and the text should be lighter IMO.

OS: Android 10
Version: Release 0.1.13

![Screenshot_20210826-232548.png](https://user-images.githubusercontent.com/83190128/131044503-bc9a7b1f-04e6-47a6-a38c-ebfa6e38c76d.png)

**Comment by ereio** [comment]
<img width="400" alt="Screen Shot 2021-09-12 at 11 20 58 PM" src="https://user-images.githubusercontent.com/14258175/133019164-e947e28e-ba76-4bd4-9635-367a53473dc6.png">

**Comment by 0x1a8510f2** [comment]
Lookin' good! :D
