### ISSUE TITLE
Unable to correctly show Chinese Characters

### ISSUE THREAD

**Issue by shanoaice** [syphon-org/syphon#339]
![Screenshot_20210829_192001](https://user-images.githubusercontent.com/25174488/131248641-219aa525-92ef-4eea-a0d3-cc73581e5450.jpg)
It seemed like that syphon is using ISO8859-1 encoding to read the message, but the message is actually encoded with UTF-8, making this app virtually unusable for Chinese speakers

**Comment by ereio** [comment]
This should be fixed in version 0.1.14 upon release. Let me know if you still see this issue. Thanks!
