### ISSUE TITLE
Reaction emojis bottom right cut off

### ISSUE THREAD

**Issue by valentinleistner** [syphon-org/syphon#342]
=> adjust scale?

![88C6D4BB-7E59-4320-B604-2BF7F8C6601E](https://user-images.githubusercontent.com/77448526/132022523-2882c846-b96c-473f-abc8-421dc7e7fde8.png)

**Comment by rstarritt** [comment]
![Screenshot_20211029-155939](https://user-images.githubusercontent.com/35974960/139506190-98ba0925-d9ad-4260-9ce9-db9b9f2db289.png)
This issue is still present on version 0.2.1 on Android 12
