### ISSUE TITLE
Format Exception

### ISSUE THREAD

**Issue by Florian-Sabonchi** [syphon-org/syphon#356]
![Screenshot_20210906-234555_Syphon](https://user-images.githubusercontent.com/54689374/132262279-9cfe0827-355a-4ec6-b3d2-ee260ce9829c.png)

Hello, I get this error after registering with KDE Homeserver. I suspect this error occurs when clicking multiple times on the request for a confirmation email

**Comment by ereio** [comment]
Fixed this issue in #338. Created 2 accounts under kde.org to resolve this issue. Thanks! 👍
