### ISSUE TITLE
Syphon Android pasting from clipboard on opening chats

### ISSUE THREAD

**Issue by daeluk** [syphon-org/syphon#396]
I have enabled showing a message when an app is accessing the clipboard on my Android 12 device.

I have noticed syphon pasting from the clipboard when I open a chat for the first time after starting the app.

I could try and look into this, although I am not familiar with the codebase at all.

This is syphon `0.2.0` from fdroid running on a Google Pixel 4a with GrapheneOS (AOSP version 12).

**Comment by ereio** [comment]
I'm using GrapheneOS on a Google Pixel 5 and have noticed this as well. Not sure what is causing this, but I've found a way to recreate the same issue in Slide For Reddit on Android. Been trying to find a determinant way to recreate it in Syphon in hopes to find whats triggering it. My guess right now is a weird side effect of the way Activities in Android are created and destroyed. Definitely looking into it.

**Comment by ereio** [comment]
Happening to everyone right now. It's blocked by Flutter. Once the fix is in Flutter's `Stable` branch, I'll update.

https://github.com/flutter/flutter/issues/74139#issuecomment-933391791

Lemmur:
https://github.com/krawieck/lemmur/issues/287

**Comment by 0x1a8510f2** [comment]
Fixed by upgrading flutter so this should probably be closed now
