### ISSUE TITLE
Animations are clunky

### ISSUE THREAD

**Issue by yephny** [syphon-org/syphon#425]
Even a basic scrolling (even before going far back in chat history) action feels slow.

**Comment by ereio** [comment]
I see this happen a lot after backfilling messages with a `limited` sync - usually after the first few times you cold open the app. I'm hoping to release an improvement to stop this from clogging up state in the next release.

Let me know when you're experiencing this and the version you're on just in case.

Thanks for bringing this up and hope to have a fix soon!

**Comment by yephny** [comment]
I created a new account, searched for a channel / chatroom and started experiencing this "issue" right away.

Android 10, Syphon v.0.2.2.
