### ISSUE TITLE
Disable encrypted disk storage

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#429]
It should be possible to not use encrypted disk storage. It can cause performance issues and **drain the battery** on older phones. It should be asked before login to use it or not.

**Comment by ereio** [comment]
Based on benchmarks from Drift, it should only affect performance by a 15% slowdown when using sqlcipher. There's likely other issues at play slowing stuff down. I'll check this along with the other research regarding the issue that have cropped up since the storage migration.

**Comment by ereio** [comment]
Not going to disable this, but performance improvements from #423 should resolve the performance concerns here
