### ISSUE TITLE
Set proxy before login

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#432]
There is no option to set proxy before login, so the initial sync request exposes the IP address to the server.

**Comment by 0x1a8510f2** [comment]
Can't currently check, but I believe this issue has specifically been addressed by @EdGeraghty. There should be an icon on the login screen which lets you set proxy settings.

**Comment by EdGeraghty** [comment]
![image](https://user-images.githubusercontent.com/20861699/146655616-6a56fb4d-30c8-4c41-9223-73c165ab35dc.png)

**Comment by ereio** [comment]
Yes, this should already be possible. Going to close unless @notramo means something else in regards to this feature

**Comment by notramo** [comment]
@ereio Sorry for the late reply. I haven't been able to test it. I don't see that option. Where can I find it?

Is it implemented in v0.2.3? I guess, yes, because I find it in the settings.

Maybe screen size issues?

**Comment by notramo** [comment]
Sorry, I see it's fixed on latest nightly build.
