### ISSUE TITLE
Incorrect session ID

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#435]
When logging in multiple times from Syphon on the same phone, it doesn't create different session IDs.
Log in, delete app data without logging out, then log in again. Only one Syphon is shown in the device list. Does Syphon reuse session ID?

**Comment by ereio** [comment]
It shouldn't. This was a previous issue but I forced it to assign a new one after each login and haven't touched it since the change worked. Perhaps something has changed with creating session IDs. I'll check

**Comment by ereio** [comment]
closed by #458
