### ISSUE TITLE
Can't scroll back in chat

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#449]
I can only view 10-30 messages. Probably pagination doesn't work.
When scrolling back, and I reach the currently loaded oldest message in the timeline, it shows the loading indicator, then it disappears without loading anything.

Tested on v0.2.3 and storage-isolate nightly.

**Comment by ereio** [comment]
this was encrypted chats only and was due to a bad cache check rule

**Comment by ereio** [comment]
closed by #458
