### ISSUE TITLE
Hide send button if there is nothing to send

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#451]
Currently, the send button is disabled if there is no text in the message composer. It should be hidden instead.

**Comment by ereio** [comment]
we've agreed to move forward with this but follow the same style as Signal without the animated tradition of the plus button to inside the text field

**Comment by notramo** [comment]
@ereio what about simply hiding the button, when composer is empty, and popping it up without animation, when text is entered?
Empty composer:
![image](https://user-images.githubusercontent.com/26059643/147386296-583b8631-9c96-4aa3-a0e7-0a26e3343658.png)
User starts typing in message:
![image](https://user-images.githubusercontent.com/26059643/147386263-fa23dcae-c1d3-4934-bf5d-2f8c78dc686e.png)

**Comment by notramo** [comment]
As discussed with @0x1a8510f2, the composer is too narrow on small screens when both buttons are shown.
However, showing both buttons can be useful if the user is composing a message, and want to send media, without deleting the draft, then continue composing the message.

So, on narrow screens, the Send button should replace the Media button, but on wide screens, both buttons should be active (as it is on the mockup).

**Comment by ereio** [comment]
like to follow something similar to Signal's designs on this one if we're going to make a change here. The plus symbol is included in the text input field, but when no text is present, it replaces the send buttom with a plus symbol keeping the background color the primary color

**Comment by EdGeraghty** [comment]
Fixed by #580
