### ISSUE TITLE
Hide encryption lock icons

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#452]
The lock icons are redundant, and are cluttering the interface.
If a message is unencrypted in an encrypted room, show a red or yellow exclamation mark with the text "unencrypted".

![image](https://user-images.githubusercontent.com/26059643/146943351-5f77938f-9316-4a93-bd7d-9d7c4a9b220f.png)

**Comment by ereio** [comment]
The message metadata should only be appearing in the final message if they've been sent within the last 2 minutes. This i think is actually a bug. Will check it out

**Comment by ereio** [comment]
closed by #458
