### ISSUE TITLE
Link opening broken (sometimes)

### ISSUE THREAD

**Issue by 0x1a8510f2** [syphon-org/syphon#456]
When clicking on links, some installations consistently show the warning but don't open the browser while others consistently successfully open the browser.

For reference:

- https://matrix.to/#/!ItaJSDCgnBOzXUBEDO:matrix.org/$tRh7awTmxaJ59VXt4g9lScs1Cdsbi-mANZcipoGFNQ0?via=0x1a8510f2.space&via=matrix.org&via=mozilla.org
- https://matrix.to/#/!TuUZlBCzpspzkrTASf:matrix.org/$MAkgYgZDDkeS9pndqP9QZt9vL8yyIOMF79R0nkNWOmc?via=0x1a8510f2.space&via=matrix.org&via=tchncs.de

Working:
- Mine:
  - Syphon 0.2.3
  - Android 10 (stock)
  - Dendrite
  - Encrypted and unencrypted
  - Brave Browser

Not Working:
- louahgoo:
  - Syphon 0.2.3 (assumed, described as "latest")
  - Graphene OS
  - Pixel 4a
  - Synapse (matrix.org)
  - Bromite Browser

**Comment by ereio** [comment]
Was a result of Android 11 privacy improvements and needing permissions to check if URLs could be opened
