### ISSUE TITLE
Messages showing up out of order

### ISSUE THREAD

**Issue by 0x1a8510f2** [syphon-org/syphon#457]
As discussed in the dev room. Opening an issue to keep track of the problem.

Currently managed to reproduce in the testing room: https://matrix.to/#/!jytfogbEdlBAKbKuWV:mozilla.org/$0VXkRVmxrxTgMi-yYF8O6ZulwKdkkRXKEn_w9twSh4s?via=0x1a8510f2.space&via=matrix.org&via=mozilla.org

**Comment by ereio** [comment]
curious if it has to do with this commit

https://github.com/syphon-org/syphon/commit/5376ff4f5a4e5974061985240b64597e89ed61d6

**Comment by EdGeraghty** [comment]
FWIW I've not encountered this in quite a while now. I vote to close this ticket, we can always reopen it if it rears its head again
