### ISSUE TITLE
Import / Export Session Keys

### ISSUE THREAD

**Issue by ereio** [syphon-org/syphon#46]
Relatively straight forward, but will need group E2EE before this should be done.

Otherwise I'll ruin peoples group chats if they attempt to talk within them.

**Comment by grravity** [comment]
Do you have an estimate on when this would be done curiously? Would be nice as you essentially cannot read chats that are E2EE (yes I understand alpha)

**Comment by ereio** [comment]
It's coming right after I finish the cache overhaul. I want to make sure the app is stable enough before I allow others to import/export key sessions.

**Comment by grravity** [comment]
Any updates on this? I see the options but they're grayed out

**Comment by ereio** [comment]
Still would like to further stabilize the app before letting people import/export. I may enable them with a warning dialog as I did get this working when importing/exporting from a file. Either way, I've pushed it as the next feature after Cross Signing #126, which is the next feature for version 0.1.7. 

I'll be running through all the history of Element E2EE edge cases / bugs over the next month and will hopefully feel more confident about unlocking it. (They just had another big edge case fix)

Just want to make sure I don't ruin peoples chats! :)

**Comment by infocilla** [comment]
Hi,
Any news on this feature ?
I started using my own Matrix homeserver a2 months ago and am pretty excited to use it ! However I can't currently use Syphon as all the chats I started are E2EE.
Thanks

**Comment by 0x1a8510f2** [comment]
@infocilla as far as I'm aware, this is currently being worked on but without an ETA.

**Comment by ereio** [comment]
I had hoped to get it out this weekend, but I think it's likely going to get pushed to next weekend. The basics of the code is there, just needs testing and QA. Should be out soon!

**Comment by infocilla** [comment]
Thanks a lot !

**Comment by constraintAutomaton** [comment]
At least on my end I'm not able to get to export the encryption key, it wait for a while and nothing happen, I don't see a file or the key anywhere.

**Comment by dnisbetjones** [comment]
> At least on my end I'm not able to get to export the encryption key, it wait for a while and nothing happen, I don't see a file or the key anywhere.

This may be related to a permissions issue. Check that you've granted filesystem permissions

**Comment by constraintAutomaton** [comment]
> > At least on my end I'm not able to get to export the encryption key, it wait for a while and nothing happen, I don't see a file or the key anywhere.
> 
> This may be related to a permissions issue. Check that you've granted filesystem permissions

Kind of, I was expecting the file to be displayed into the new document section but it was not, it was in simply in my document folder.
