### ISSUE TITLE
bug: newline is not respected

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#483]
When inserting a newline in the composer, it's displayed in one line in the sent message.
This is correct according to original Markdown spec, but most platforms use a different flavour. Also, for beginner users, who don't know Markdown, an *italic*, or **bold** formatting, maybe a bullet list can be an interesting easter egg, but removing newlines (which are used for logically separating text) is not good UX.

**Comment by EdGeraghty** [comment]
Fixed by #590
