### ISSUE TITLE
sso: could not launch ...

### ISSUE THREAD

**Issue by sp1ritCS** [syphon-org/syphon#492]
pressing the "single sign on" button throws an error message: "Could not launch https://singlesignonprovider.tld". I've tested both private and public instances and it happens to all of them.

Android 11 w. F-Droid version of Syphon. 

Might be becaue of using a nonstandard webview (bromite/fenix) provider.

![Screenshot_20211230-203422_Syphon](https://user-images.githubusercontent.com/31540351/147782905-fdccdd45-67f2-4465-83b3-142513986a91.png)

**Comment by ser** [comment]
On my current release syphon from play store SSO is not even offered. Element logs in without an issue.

**Comment by ereio** [comment]
I believe this is due to a recent update with Android 11 that requires a lot more app permissions around opening links. I haven't had time to look into the issue here, but hope to have an update out soon.

**Comment by junocomp** [comment]
I am also having this issue on Linux. Is there a work around?
