### ISSUE TITLE
Remove Exif information

### ISSUE THREAD

**Issue by Florian-Sabonchi** [syphon-org/syphon#496]
As it appears, Syphon does not currently remove exif information. We should remove them for security reasons

**Comment by mpfaff** [comment]
I agree that exif information should be removed for privacy, but sometimes I want to keep exif information when I send an image. For this reason, I think it should be the default, but optional.

**Comment by ereio** [comment]
Adding it as the default now but without a toggle setting at first. I'll make another issue for toggling it off.
