### ISSUE TITLE
Sign up flow broken

### ISSUE THREAD

**Issue by bwedl** [syphon-org/syphon#497]
Hi, I am getting stuck when trying to sign up to the matrix.org homeserver using Syphon.

**Steps to reproduce**

1. _count me in_
2. Choose matrix.org as homeserver
3. Walk through sign up process until _Confirm you're alive_
4. _Load Captcha_

> Screen will remain greyed out.

<img width="304" alt="Screenshot 2022-01-06 at 08 17 32" src="https://user-images.githubusercontent.com/88787929/148345060-4d8f1f7c-1635-4e2e-a74b-ed8004c674d7.png">

**Expected**
Continue the sign up flow successfully loading Captcha and completing.

**Comment by jhpgcj** [comment]
This also happens on mobile. Using version 0.2.6, F-Droid build, on Android 11.
