### ISSUE TITLE
Only show the "Terms and conditions" pop-up the first time the user opens Syphon  

### ISSUE THREAD

**Issue by simplepad** [syphon-org/syphon#519]
Showing this pop-up every time the user logs out is a bit excessive, it becomes annoying and encourages the user to skip it without reading and pay less attention to the information provided by it.

**Comment by notramo** [comment]
It also encourages muscle memory behavior for skipping texts.

**Comment by ereio** [comment]
in with https://github.com/syphon-org/syphon/pull/568/files
