### ISSUE TITLE
bug: reading messages in Element show it as unread in Syphon

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#534]
reading in Syphon -> Element marks it as read (and Element notification disappears)
reading in Element -> Syphon shows it as unread (can't say anything about notification as it doesn't work #535)

The problem is probably that it doesn't sync read markers from server.

**Comment by EdGeraghty** [comment]
Fixed by #548

**Comment by EdGeraghty** [comment]
Closed by #548
