### ISSUE TITLE
bug: background notification service doesn't work on Android

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#535]
The foreground notification ("listening for new messages" or similar) is not displayed on Android. It worked in previous releases (although I don't know what release messed it up).

**Comment by simplepad** [comment]
@notramo Android version?

**Comment by notramo** [comment]
Yes.

**Comment by simplepad** [comment]
No, I mean which one, Android 12? :)

**Comment by notramo** [comment]
Android 11 (Lineageos 18.1)
