### ISSUE TITLE
Question about i18n

### ISSUE THREAD

**Issue by EldersJavas** [syphon-org/syphon#552]
I cannnot use matrix, sorry

### Hello, everyone

I try to translate syphon into Chinese on https://hosted.weblate.org/projects/syphon/syphon/  
Is that going to be added in app ?  
If not, Or I need translate completely ?  

Thanks a lot,  
EldersJavas

**Comment by 0x1a8510f2** [comment]
Any translations you add on Weblate will be added to the app when they are approved (the pull request by Weblate is merged). You don't need to translate it fully for your translations to be added. Hope that helps! :D
