### ISSUE TITLE
[Improvements] minimize media access after having sent media

### ISSUE THREAD

**Issue by hollisticated-horse** [syphon-org/syphon#553]
Currently, after having sent an image or other, the media sending part stays expanded.
![testing_media_sending](https://user-images.githubusercontent.com/76632257/152663335-12a8226b-55d7-4f62-b4c9-1056009fc028.jpeg)

 
I think it would be more practical to minimize it back after having sent the media in question to be able to quickly to continue sending textual messages

**Comment by ereio** [comment]
fixed with https://github.com/syphon-org/syphon/commit/b3b2d12b61f50b4605530b08dec96421d480b966

good catch!
