### ISSUE TITLE
[Feature Request] pinning chats to the top

### ISSUE THREAD

**Issue by hollisticated-horse** [syphon-org/syphon#555]
Could we implement pinning chats to the top and have them stay there what ever happens. High priority of sorts.

**Comment by ereio** [comment]
Chat lists will take care of this, there's a branch with work for it already. I can make a issue describing it

**Comment by hollisticated-horse** [comment]
Maybe ? Or do it here ? I can change the title if you want.

**Comment by ereio** [comment]
made a new ticket to track #575
