### ISSUE TITLE
[Improvement] Adding a random id to media file name sent with Syphon ?

### ISSUE THREAD

**Issue by hollisticated-horse** [syphon-org/syphon#558]
Currently the renaming convention for any images is : `media-default-scrubbed.jpeg`. However, when downloading the file, it quickly becomes problematic because each new file needs to be renamed or it overwrites the previous image/media.

Is it by design ? We could have a random id added to the name, to avoid having to systematically rename files ?

**Comment by ereio** [comment]
was a bug, good catch! The files names being sent now are usually temporary due to how the libraries work regarding access. Another ticket could be retaining their original names 👍

closed with https://github.com/syphon-org/syphon/commit/9ffd9bd341f75dc432851b3a01ccdc7f15912f95
