### ISSUE TITLE
Use package: matrix_homeserver_recommendations for setup

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [syphon-org/syphon#559]
In order to get a more reliable and up-to-date timeserver selection during the setup, I would propose to use the [`matrix_homeserver_recommendations`](https://pub.dev/packages/matrix_homeserver_recommendations) Dart package rather than the predefined JSON list.

This package has originally been written for FluffyChat but should perfectly work with Syphon too.

**Comment by simplepad** [comment]
related to https://github.com/syphon-org/syphon/issues/256

**Comment by ereio** [comment]
We - until very recently - were using [hello-matrix](https://www.hello-matrix.net/public_servers.php) (the json payload version) to return up-to-date information on several servers. A lot of people wanted to keep the recommendation list bundled with the app to prevent out-of-band network calls to other services to retrieve the list and general reliance on it.

That said, I do like the library you've created! Keep up the good work!
