### ISSUE TITLE
Delete chat locally by one click

### ISSUE THREAD

**Issue by AnisTaluqdar** [syphon-org/syphon#564]
I know it is not possible but I think it is possible by hiding that chat. Whenever someone clicks the delete button it can hide the chat from locally, not as an archive.  And again whenever that person dm it can start a conversation in that room but not show the previous text locally. 

And when the user wants to delete the chat it can warn the history is remaining other client as well as other person. 

This thing is needed because in other messaging app we sometimes want to delete the chat and want to start a conversation again but in mattix, it is not possible you need to leave the room. But history also remains the same way.

**Comment by EdGeraghty** [comment]
Does the chat deletion long-press not do what you want?
![leave](https://user-images.githubusercontent.com/20861699/154507113-7d30c780-55e3-4bed-a0ff-6a082df7484b.gif)

**Comment by AnisTaluqdar** [comment]
there have a delete button. hmm, and most of user they want to delete chat without leaving the room, but currently it's not possible any matrix client. So, that's what I wanted.

**Comment by ereio** [comment]
this was meant to be the point of "archive". Basically a local delete only. You can visit the "archive" screen if you ever want to un-archive the chat and see it in the home view again

**Comment by ereio** [comment]
note #78

**Comment by ereio** [comment]
going to close this unless Archive wouldn't serve the need here, but it sounds like it would.

It wouldn't leave the room on the server, but you wouldn't receive any updates or see the room in your normal chat list under Syphon

you could always visit "Room Archive" in settings and interact with it like any other room, and un-archive it if needed
