### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by Akpenyo** [syphon-org/syphon#566]
hello Team ,
   I am trying to run the iOS version of the app and I get this error l

**ib/global/platform.dart:41:23: Error: Member not found: 'PathProviderLinux.register'.
    PathProviderLinux.register();**

what am I missing

**Comment by EdGeraghty** [comment]
I'm having a similar error in my IDE, so I'm not quite sure what's changed but it has affected me too....

![image](https://user-images.githubusercontent.com/20861699/154076733-377cfc3d-ea0a-46d1-8bce-f15c0c5ae977.png)

**Comment by ereio** [comment]
Which version of Flutter are you using to build with? Make sure you're on version `2.8.1` of Flutter. We'll be upgrading to 2.10+ soon but we're trying to stabilize a few more things before taking on the breaking changes associated with it!

**Comment by ereio** [comment]
Ran into this after forcing an update to path_provider. We were previously using 2.0.1 and it seems they added a breaking change around 2.0.9. I'll remove the `^` to force the version used explicitly, especially if patch version updates are going to introduce breaking changes. Sorry for the confusion!
