### ISSUE TITLE
Dark mode isn’t remembered

### ISSUE THREAD

**Issue by TimestaticYT** [syphon-org/syphon#573]
Dark mode isn’t remembered after closing and reopening the app on iOS

**Comment by EdGeraghty** [comment]
Which version are you on? I believe this was a bug which has been fixed...

**Comment by TimestaticYT** [comment]
Im currently on the most recent version on the iOS App Store 0.2.6
If there’s a new version I’d be cool to see it being updated

**Comment by TimestaticYT** [comment]
It now remembered it for me. Seems like it only remembers after you leave the settings page you’re on. Otherwise it won’t get saved or something. Just worked for some reason for me

**Comment by ereio** [comment]
This should have been fixed after 0.2.6, but I haven't updated the App Store version in a long while. I'll leave it open until the 0.2.9 release just in case

**Comment by EdGeraghty** [comment]
Hopefully this has been solved with refactoring since 0.2.6 - since we've seen nothing on here for nearly a month, I'm going to close this ticket. If it's still a problem we can always reopen.
