### ISSUE TITLE
White screen when trying to deactivate account, cant delete account

### ISSUE THREAD

**Issue by TheOnlineRando** [syphon-org/syphon#582]
I downloaded Syphon from F-droid, made a matrix account. when i try to deactivate it, i confirm the prompts and i see a white overlay thats just barely transparent, and nothing happens. i can press the back button on my phone and the white goes away, account doesnt delete.

**Comment by ereio** [comment]
was just fixed in a recent commit 80a6114988076b3404a8756b11bd5e3297dabd0c and will be going out in the version 0.2.9 release. Sorry for the trouble and thanks for reporting it!
