### ISSUE TITLE
Ability to use HTTP (without ssl) for public URL

### ISSUE THREAD

**Issue by jamm1985** [syphon-org/syphon#583]
It will be a good option to setup home server to use public URL with pure HTTP. Right now it is impossible and app try to connects with https all the time. May be it is reasonable to parse port in home server URL or provide an settings to pick up home server URL on login page.

**Comment by ereio** [comment]
Yeah I don't think we should allow this in particular. We've had several requests for features like this that are not secure and even some I'm considering adding under `Advanced` settings alongside non-production builds only (like Nightlies). 

This one, however, is not one we'll support even in that context; you should really enable TLS or use a homeserver that does. 

Let us know if you need suggestions for a homeserver that does. Feel free to let us know if you have any other concerns with this or have other examples where this could exclude a large part of the matrix community. 

You're always free to run your own personal build and replace the `https://` instances with `http://` :) I can parametrize the `https://` protocol reference as a `const` to make it easier to replace if you'd like / if that's a solution that will work for you. Let me know!
