### ISSUE TITLE
macos build not running on 10.15.7

### ISSUE THREAD

**Issue by dzg** [syphon-org/syphon#586]
Trying to run macos build: 
```
You can’t use this version of the application “Syphon.app” with this version of macOS.
You have macOS 10.15.7. The application requires macOS 11.0 or later.
```

<img width="532" alt="image" src="https://user-images.githubusercontent.com/466557/155183913-a0c2e9cf-2ffd-45fa-aabf-9155922b27f4.png">

**Comment by ereio** [comment]
will bump this down soon, just waiting for our latest release to stabilize
