### ISSUE TITLE
Switch dark / light theme based on system preferences

### ISSUE THREAD

**Issue by trosel** [syphon-org/syphon#588]
Rather than cycling between Light / Dark / Darker / Night, I'd like to be able to choose between 

1. Light
2. Dark
3. System

(I would personally choose System)

**Comment by ereio** [comment]
approved for adding System as a preset

**Comment by EdGeraghty** [comment]
A quick investigoogle turns up https://stackoverflow.com/questions/56304215/how-to-check-if-dark-mode-is-enabled-on-ios-android-using-flutter
