### ISSUE TITLE
Wordle results are not rendered correctly

### ISSUE THREAD

**Issue by trosel** [syphon-org/syphon#589]
We have to get our priorities right here 😁

![349A1D6D-A845-46A1-827F-AFF5587C9B0A](https://user-images.githubusercontent.com/1299322/155388557-77296f47-4768-4e9e-9217-1742a751e4b3.jpeg)

the message looks like so

Wordle 249 5/6

🟨🟨⬛⬛⬛
⬛⬛🟩🟨🟨
🟩🟩🟩⬛⬛
🟩🟩🟩⬛⬛
🟩🟩🟩🟩🟩

maybe Syphon isn’t detecting line breaks?

**Comment by ereio** [comment]
lmao I'll take a look! 

We should have line break support though; I write markdown lists fairly often and I usually prefer to do so in Syphon.

**Comment by 0x1a8510f2** [comment]
Complete guesswork, but maybe this has something to do with DOS and Unix newlines where one is supported and the other isn't?

**Comment by EdGeraghty** [comment]
![image](https://user-images.githubusercontent.com/20861699/155416348-fc24c279-9866-49e0-972e-0ffd228f86b6.png)

Weirdly, editing the message makes it display the line breaks properly!

**Comment by EdGeraghty** [comment]
![image](https://user-images.githubusercontent.com/20861699/155423600-e921052c-4d91-4e97-925c-a20fb67e5cb6.png)

**Comment by ereio** [comment]
🎉

**Comment by trosel** [comment]
i wonder if they will fix that since NYT devs are working on it now
