### ISSUE TITLE
The touch area for unloaded images is to small and centered

### ISSUE THREAD

**Issue by hollisticated-horse** [syphon-org/syphon#592]
# What is happening:

On mobile, when tapping an unloaded image, you have to real tap the icon for image. The empty area inside the chat bubble around the icon don't react. 

![signal-2022-02-24-003408](https://user-images.githubusercontent.com/76632257/155429332-f5239e85-24b2-4d41-a777-0371e3f68701.png)

# Expexted Behaviour: 

When tapping on the bubble with the unloaded image, it should load when tapped, even the empty area around the unloaded image icon.

Version: 0.2.9 Android

**Comment by ereio** [comment]
is an improvement, but is also a bug
