### ISSUE TITLE
[Flatpak] Graphical glitches appear on screens with art assets

### ISSUE THREAD

**Issue by dnisbetjones** [syphon-org/syphon#606]
**Version:** Flathub 0.2.10
**OS:** elementaryOS 6.1

On the welcome screen & subsequent onboarding screens there are random colour swaths and graphical glitches when the art assets appear. See photo below:

![signal-2022-02-28-144320_001](https://user-images.githubusercontent.com/64179257/156071272-056ac174-1b8a-4d81-bf47-6880402ce2ef.jpeg)

If you scale the window, the glitches rearrange or disappear.

**Comment by 0x1a8510f2** [comment]
Hmm, that's a weird one. I can't reproduce on Ubuntu 20.04 in QEMU with the same version. Resizing the window has no impact either.

<details>
<summary>
Screenshot
</summary>

![image](https://user-images.githubusercontent.com/83190128/156071822-d7d031ce-ccde-401f-8a97-20c4db9e9900.png)

</details>

**Comment by dnisbetjones** [comment]
I will test another Linux machine tonight running Linux Mint and if the issue doesn't exist there, I will chalk it up to a machine & distro-specific bug and close it. Thank you for verifying that.

**Comment by 0x1a8510f2** [comment]
No problem. Perhaps it's some kind of GPU driver issue? In any case, I'll wait for your results and I'll look into it some more if you or anyone else is able to reproduce it.

**Comment by dnisbetjones** [comment]
Confirmed that this is a system-specific issue and will close this.
