### ISSUE TITLE
Theme not being saved?

### ISSUE THREAD

**Issue by EdGeraghty** [syphon-org/syphon#608]
Every time I restart Syphon I'm kicked back to the light theme

**Comment by EdGeraghty** [comment]
Windows & Android (both tracking upstream ` Dev `)

**Comment by EdGeraghty** [comment]
Is this #573 rearing its head again?

**Comment by 0x1a8510f2** [comment]
Awesome. That's one less thing for me to worry about :P

**Comment by EdGeraghty** [comment]
![image](https://user-images.githubusercontent.com/20861699/156208390-054002d1-427f-40b6-8d69-a3bb03f80cc0.png)

I may actually be bitten by my own work haha, this may not be a bug at all 🙈

**Comment by EdGeraghty** [comment]
It might. Because I've just rebuilt the JSON stuff and it saves between sessions now... 🙈

**Comment by 0x1a8510f2** [comment]
So much for that feeling of relief I had :(

**Comment by EdGeraghty** [comment]
Sorry!
