### ISSUE TITLE
macos build 0.2.10 still not running on 10.15.7

### ISSUE THREAD

**Issue by dzg** [syphon-org/syphon#621]
Trying to launch latest macos build 0.2.10: 
```
You can’t use this version of the application “Syphon.app” with this version of macOS.
You have macOS 10.15.7. The application requires macOS 11.0 or later.
```

<img width="532" alt="image" src="https://user-images.githubusercontent.com/466557/155183913-a0c2e9cf-2ffd-45fa-aabf-9155922b27f4.png">

**Comment by dnisbetjones** [comment]
I believe this is related to #613 which has been merged but may only come with the next release. Tagging @ereio to confirm.

**Comment by ereio** [comment]
yes, this should be fixed with the 0.2.11 release. I can post a prebuild here if you're willing to test it @dzg

you should also be able to pull from `dev` and see the same results after building. let me know!

**Comment by dzg** [comment]
Sure @ereio  happy to test a build!

Thanks

**Comment by ereio** [comment]
Sorry this took so long! I ended up needing to release 0.2.11 a little early to clear out the FDroid build issues.

Let me know if the following build works or not for you

Either way, we'll figure it out! I noticed where the minimum version was being replaced / ignored by the Flutter build script so I know where to look now if it's still being mischievous 

https://github.com/syphon-org/syphon/releases/download/0.2.11/syphon.macos.0.2.11.zip

**Comment by dzg** [comment]
Sadly, same error ... and app has the 🚫 overlay

**Comment by ereio** [comment]
hey @dzg, can you check one last time on the recent build I've uploaded under the 0.2.11 release?

https://github.com/syphon-org/syphon/releases/download/0.2.11/syphon.macos.0.2.11+2.zip

@dnisbetjones has tested and said it worked for them under Catalina. lmk and thanks for all your help!

**Comment by dnisbetjones** [comment]
I will close this issue as I think it can be considered resolved. @dzg if you want to follow up with us later, don't hesitate.
