### ISSUE TITLE
Don't crop image in timeline

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#631]
Images are cropped to a square in the timeline. This doesn't look good, and has usability issues. They shouldn't be cropped. If an image is e.g. a mobile screenshot (taller), then it should scale down, and display it in a narrower bubble instead of cropping. This is what Element does.

**Comment by ereio** [comment]
This was mirroring the UX in Signal as they are cropped to a square. It helps keep the amount of computations for rendering the message list low by treating all image message bubbles the same same size. However, I think we could add a mode to render the image inline (without a bubble) if the user wants which could show a more natural image height and width. lmk your thoughts on this, but wouldn't want to remove the square crop for now.

**Comment by 0x1a8510f2** [comment]
Fine with the square crop personally. It seems quite common in apps, I know Reddit does it too. As long as "click to enlarge" is available, it shouldn't be much of an issue. Also probably helps deal with weirdly-sized images. I saw FB messenger struggle with this sometimes.

**Comment by ereio** [comment]
We have tap to view now that has pinch to zoom and other features for better viewing. Closing this as the image preview should be consistently sized to maintain chat performance
