### ISSUE TITLE
Some strings are not displayed.

### ISSUE THREAD

**Issue by eshagh79** [syphon-org/syphon#639]
Some strings are not displayed. And instead a string id is displayed.
I am using syphon 0.2.8 (2010).
Android 5.1.1
The first screenshot is of a group info page and the second screenshot is of a user info page.

![Screenshot_۲۰۲۲-۰۳-۲۲-۱۰-۵۸-۰۱](https://user-images.githubusercontent.com/52137191/159424651-141f08d3-6e6f-4877-9c41-cfe92e9c8d1b.png)
![Screenshot_۲۰۲۲-۰۳-۲۲-۱۰-۵۴-۴۹](https://user-images.githubusercontent.com/52137191/159424655-9d23dd35-459f-4b68-81ee-083634fac486.png)

**Comment by ereio** [comment]
this should be fixed in the upcoming 0.2.12 release if not an earlier one. let us know if you still see this upon the next release!

**Comment by eshagh79** [comment]
Thanks, these two issues with 0.2.12 have been fixed
