### ISSUE TITLE
Key backup fails when Documents folder doesn't exist

### ISSUE THREAD

**Issue by 0-st** [syphon-org/syphon#645]
It works again after manually creating the folder.

**Comment by dnisbetjones** [comment]
Hi there, @0-st thanks for the report. Can you give some more details on what version of Syphon you are running and what platform?

**Comment by ereio** [comment]
Can confirm this should be happening on all Android phones. It assumes this directory exists. Going to add a setting to change the directory and ideally ask before the export if it doesn't exist.
