### ISSUE TITLE
Error in the naming of rooms

### ISSUE THREAD

**Issue by Florian-Sabonchi** [syphon-org/syphon#650]
As it looks, groups are named after users. 
![IMG_20220406_185011_361.jpg](https://user-images.githubusercontent.com/54689374/162026590-15e792ab-40b3-4318-8c55-27beb494302f.jpg)

**Comment by notramo** [comment]
Maybe related to #524

**Comment by ereio** [comment]
potentially fixed in #677, let me know if you continue to see it after version 0.2.14

**Comment by Florian-Sabonchi** [comment]
Hello, thanks for reply nerver Seen since Version 0.2.14. Do you know what the reason was?
