### ISSUE TITLE
Some settings are not saved

### ISSUE THREAD

**Issue by alekseishaklov** [syphon-org/syphon#662]
**Greetings! 👋** 

_**Problem:**_
I want to use this matrix client, but it is very inconvenient.
Settings in some sections (Chats and other) are not saved after restart, i. e., language settings. App says that i will need  to close and restart it to take effect. I choose my language, close app (I tried it with and without closing the settings), start it again, and I don't get any results.

**_App version:_**
0.2.12 [binary](https://github.com/syphon-org/syphon/releases/tag/0.2.12) for Linux

**_OS version:_**
Debian GNU/Linux 11

**Comment by 0x1a8510f2** [comment]
Possibly related to https://github.com/syphon-org/syphon/issues/659

**Comment by cintek** [comment]
@ereio it seems that this issue wasn't closed automatically by Github. Maybe you could do it to clean up the issue list?
