### ISSUE TITLE
Leaving rooms on other clients is not reflected in Syphon

### ISSUE THREAD

**Issue by EdGeraghty** [syphon-org/syphon#664]
Leave a room in Element, and you're still in there in Syphon

**Comment by dnisbetjones** [comment]
Can confirm this bug is happening for me, too. It also applies to DMs.

**Comment by 0x1a8510f2** [comment]
Just a guess, but this might be because the room is still in account data. I think Element doesn't clear whether the room is a DM etc. when leaving the room.

**Comment by EdGeraghty** [comment]
I'm actually wondering how much is due to the hot cache. This is likely to cause issues with #660, no?
