### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [syphon-org/syphon#683]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 10 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on Syphon (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Syphon's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by ereio** [comment]
They never emailed us and this looked automated based on all the other open source projects that got hit with no response. Closing for now.

**Comment by misterAnderson90** [comment]
Hello @EdGeraghty and @ereio, 

I'm sorry for not sending you the report before. I just e-mail you the privet gists I have documented. Please let me know how you perceive these warnings and whether you are interested in receiving a report with all warnings.

**Comment by notramo** [comment]
@ereio, what's the progress on this?

**Comment by ereio** [comment]
They were all false positives and unused native functions tangent to the library iirc
