### ISSUE TITLE
[Dedicated Server] Is there any open-source server for lower-scaled usage?

### ISSUE THREAD

**Issue by ryuujo1573** [syphon-org/syphon#684]
Is there any open-source **server** for lower-scaled usage?
I was wondering if I could deploy a server of my own.

Thank you. 💟

**Comment by ryuujo1573** [comment]
Sorry for bothering, I just found that Syphon uses `[Matrix]` as server.

**Comment by notramo** [comment]
@ryuujo1573 [Conduit](https://conduit.rs/) is a Matrix server written in Rust, and is designed for personal servers and low-spec hardware.

**Comment by ryuujo1573** [comment]
> @ryuujo1573 [Conduit](https://conduit.rs/) is a Matrix server written in Rust, and is designed for personal servers and low-spec hardware.

Thank you so much!
