### ISSUE TITLE
Google Translate Service

### ISSUE THREAD

**Issue by AnisTaluqdar** [syphon-org/syphon#722]
If you can add the Google Translate service it will be amazing as https://imem.app/ they add for telegram client.

It's really helpful when it comes to chatting with outside the world who don't know English.

**Comment by 0x1a8510f2** [comment]
Thanks for the suggestion!

Unfortunately, I don't think this aligns with Syphon's goals.

While this would improve ease if use, Syphon generally avoids making requests to any server other than your homeserver and tries to avoid dependence on third-party libraries. This feature would likely require an additional library and would also make requests to an external server which is far from ideal.

What's more, sending message content to Google Translate essentially nullifies the benefits of end-to-end encryption which is one of the main reasons to use Syphon in the first place.

Finally, depending on Google Translate introduces a point of centralization. As far as I know, there's no common translation API so additional effort would be required to support every new provider which is infeasible, while users will no doubt request this as soon as automatic translation is added.

I'll let the other devs chime in before closing the issue, but I doubt this is something we'll want to implement.

That said, as a possible alternative, I believe there are apps which can read your screen contents and automatically translate them. Perhaps this could work?

**Comment by EdGeraghty** [comment]
FWIW I agree with @0x1a8510f2 on this. The idea of sending the cleartext to a third-party translation server, whilst yes it would improve ease-of-use literally obviates the entire point of E2EE in the first place.

>I'll let the other devs chime in before closing the issue, but I doubt this is something we'll want to implement.

Similarly I'll let other Devs chime in, but I do agree this is unlikely to be something we'll want to implement.

**Comment by dnisbetjones** [comment]
Ultimately the decision will need to be made by @ereio but I agree that this will not align with Syphon's values or goals.

But thank you for submitting your suggestion!

**Comment by ereio** [comment]
Yes, like @dnisbetjones mentioned, thanks for the request, but I don't think we'll move forward with this. It would compromise the privacy and security of the message contents. Perhaps there might be an entirely local / offline translation library or service that might help with that, but I'm not aware of any at the moment.

That said, if one was to come along or us be made aware, I'd be open to reconsidering as long as it was entirely offline

Thank again for the consideration!
