### ISSUE TITLE
Send emojis in text messages

### ISSUE THREAD

**Issue by AdiAr11** [syphon-org/syphon#729]
Like other messaging apps like Whatsapp, user can send emojis in text messages they send.

**Comment by dnisbetjones** [comment]
@AdiAr11 Thanks for the feature request. I think it would be a nice addition. Could you share a screenshot of how you would like to see this implemented? Perhaps from an app you use that has this done in a good way.

**Comment by AdiAr11** [comment]
Sure !! I use emojis pretty often in whatsapp, I'll share screenshots of it.
![WhatsApp Image 2022-09-21 at 1 29 01 PM](https://user-images.githubusercontent.com/54585121/191449107-29ae3bd0-a8e3-41ed-9926-690e903a89f
![WhatsApp Image 2022-09-21 at 1 29 03 PM](https://user-images.githubusercontent.com/54585121/191449126-4a2a62bc-6a5d-419c-8a6d-2517e427d79e.jpeg)
9.jpeg)

**Comment by dnisbetjones** [comment]
Thank you for that, I'm sure this is something lots of people would like to see. It will need approval from @ereio

**Comment by AdiAr11** [comment]
Sure! Thank you @dnisbetjones !!

**Comment by ereio** [comment]
I thought this already existed? Happy to add the emoji button to the text input. We already have an emoji input lib in use for reactions we could use there

**Comment by AdiAr11** [comment]
Great,  Thank you !!
