### ISSUE TITLE
Be available in Huawei's AppGallery

### ISSUE THREAD

**Issue by m1chj** [syphon-org/syphon#734]
Implement HMS-based push notifications so people running new & google-free Huawei devices can also enjoy Syphon with notifications delivered efficiently in timely manner without background connection running 24/7 impacting battery life

**Comment by dnisbetjones** [comment]
Thank you for your feature request. This will need discussion with the developers to see if it aligns with Syphon's goals. I will tag @ereio for attention.

**Comment by dnisbetjones** [comment]
After discussion with the team, it was decided that integrating HMS services into Syphon would not align with our core mission and so I will close this request. It is recommended that users who wish not to use or cannot access Google Play should get Syphon from Github, F-Droid or in the future, the nightlies available on Gitea.

Thank you very much for your interest!
