### ISSUE TITLE
Flatpak missing dependency

### ISSUE THREAD

**Issue by notramo** [syphon-org/syphon#746]
There is an error when launching the Flatpak from postmarketOS, aarch64.
```
syphon: error while loading shared libraries: libjsoncpp.so.25: cannot open shared object file: No such file or directory
```

**Comment by knghtbrd** [comment]
Affects amd64, I suspect it affects all flatpak builds at the moment.

**Comment by 0x1a8510f2** [comment]
That's annoying. I'll take a look when I have some free time but it might not be for a little while.

**Comment by 0x1a8510f2** [comment]
Sorry this took so long, but should be fixed now in https://github.com/flathub/org.syphon.Syphon/pull/7 so closing as resolved. Feel free to reopen if you still encounter the issue after updating the flatpak (tested on amd64).
