### ISSUE TITLE
F-droid?

### ISSUE THREAD

**Issue by lo-yak** [syphon-org/syphon#753]
Hi! I'm exploring syphon (android) and I find it awesome! I'd really like to follow it's future development, though I noticed that the last update of the build on F-droid is one year ago, so...do I have to install a repo? Or do I have to ignore it and download Syphon from here? Just trying to understand what's going on because I'm a bit confused...
Thank you!

**Comment by dnisbetjones** [comment]
Hi there @niels0n thanks for your interest in Syphon. Unfortunately, there's an issue with the F-Droid builds at the moment so the recommended way to get the latest version is directly here. Thank you!

**Comment by ereio** [comment]
We're going to continue deploying to FDroid but we're cleaning up some other things first!

**Comment by lo-yak** [comment]
Got it, thanks!
I was just wondering if the F-droid was reliable or not, I'll just add the Github releases to my RSS feed then :D
