### ISSUE TITLE
Is there a way to ask for keys?

### ISSUE THREAD

**Issue by dewi-g** [syphon-org/syphon#757]
I'm using Syphon on Android, I started a chat with user presumably on Element (the user really propagates this app, although I cannot be sure if she actually uses it herself). It seems that the counter account can read my messages, since they have been answered, but all I see is Encrypted message notification. We have no common keys in the chat settings. Is there a way I can ask for them, so I can decypher the messages?

Additionally, my backup of keys has just failed multiple times, but I can open specific issue for that and it's not all that much an issue for me now since my keys cannot decypher the messages anyway.
Thanks and sorry for this weird inconvinience

**Comment by dnisbetjones** [comment]
Syphon currently does not have cross-signing support and your sessions will need to be manually verified from Element or elsewhere.

Please see our FAQ for some instructions on doing so: https://github.com/syphon-org/syphon/blob/dev/docs/faq-en.md#how-do-i

Don't hesitate to join us at #syphon-support:matrix.org for live support as well. I will close this issue as completed and look forward to helping you via our Matrix community.
