### ISSUE TITLE
Update dependencies in Readme

### ISSUE THREAD

**Issue by cintek** [syphon-org/syphon#763]
Hi everyone,

it would be good if someone would update the Readme with the current dependencies so that new developers can easily start with the "real" stuff.

When I built Syphon for my last commits I had to install these packages:

- libolm-dev
- libsqlite3-dev (already included in Readme)
- libjsoncpp-dev
- libsecret-1-dev
- liblzma-dev
- libgtk-3-dev
- clang

After the commit 8f3658d71f83f848fbfa48cdbf10c40d73b05763 I additionally had to install `libssl-dev`.

Can someone confirm this? I'm working in a Debian-based distro.

**Comment by 0x1a8510f2** [comment]
Thanks for bringing this up! I had a look at our [CI script](https://github.com/syphon-org/syphon/blob/dev/.drone.yml) and it looks mostly the same as the list you have here. I'll update the README and also include a note to check the CI script for up-to-date instructions if those in the README aren't working.

**Comment by cintek** [comment]
Thanks for the update!
