### ISSUE TITLE
Proxy does not work on registration

### ISSUE THREAD

**Issue by Hid-K** [syphon-org/syphon#780]
When proxy is set - it works on login, but not on registration.

**Comment by EdGeraghty** [comment]
Oops.

I'll have a look at that.

**Comment by EdGeraghty** [comment]
Found some time to look into this. Looks like both registration and our SSO login flow (which also doesn't go through the proxy) rely on handing off handling of the url to the underlying OS to open in its browser.

I think we'll have to caveat this as a limit to the functionality...
