### ISSUE TITLE
Toki Pona translation doesn't exist

### ISSUE THREAD

**Issue by Gapva** [syphon-org/syphon#786]
I switched the application language to Toki Pona in settings. Syphon then told me to reload to apply my changes. Upon relaunching Syphon, the following is displayed and I cannot bypass it without clearing all of my application data:

![Screenshot_20240201-111018.png](https://github.com/syphon-org/syphon/assets/90116898/b1ed342e-19f5-49bd-a9c3-d6ee53959643)

Sure enough, the translation file doesn't even exist in the tree at all. If it was removed because it had no proper maintainer, then I will gladly contribute to the Toki Pona translation of Syphon.

**Comment by EdGeraghty** [comment]
toki!

I was the guy originally hoping to translate Syphon to toki pona but life got in the way. Please do submit your translations, I look forward to them.

**Comment by Gapva** [comment]
> toki!
> 
> I was the guy originally hoping to translate Syphon to toki pona but life got in the way. Please do submit your translations, I look forward to them.

toki a! Will do! Am I supposed to make a PR including the JSON file, or is there a Weblate of some sort?

I'm sorry to hear that life is getting progressively busier for you, as well. mi wile sina tawa pilin pona mute lon tenpo kama o! ^^, and take care.

**Comment by EdGeraghty** [comment]
>  Am I supposed to make a PR including the JSON file, or is there a Weblate of some sort?

The project does indeed have [a hosted Weblate](https://hosted.weblate.org/engage/syphon/), although I've actually found it quicker to do it in the JSON itself and then PR. Up to you, I guess!

> I'm sorry to hear that life is getting progressively busier for you, as well.

I think it's just part of "the human condition" :smile: 

> mi wile sina tawa pilin pona mute lon tenpo kama o!

sina pona :heart:

**Comment by Gapva** [comment]
I made a PR a few days ago detailing my new Weblate contributions, along with the `tok.json` file in its proper location. About sixty percent of Syphon is now translated into Toki Pona! 🎉

I'm not sure how well-maintained Syphon is as of now (last Release tag created over a year ago), but I hope my translations will be merged and pushed if/when possible! ^^ Thank you so much in advance to any maintainer willing to do such, and to @EdGeraghty for the wonderful details regarding this issue. ❤️
